#(c) 2008 by Malte Marwedel. Use under the terms of the GPL Version 2

all:
	./make.sh
	cp cb_make_selfextracting.sh ../bin/cb_make_selfextracting.sh
	cp cb_trace_program.sh ../bin/cb_trace_program.sh
	cp cb_automatic_temp.sh ../bin/cb_automatic.sh

removebackups:
	rm -f *~

clean:
	rm -f cb_make_selfextracting.sh
	rm -f cb_automatic_temp.sh
